"""
ProxyGuard Studio — Narrative API Endpoint
==========================================
POST /api/v1/audit/{audit_id}/narrative

Called by HumanStoryPanel.tsx after the audit is complete.
Returns the Gemini-generated emotional narrative + the raw numbers
the UI needs to render the impact stats (always from the engine, never from Gemini).
"""

from fastapi import APIRouter, HTTPException
from pydantic import BaseModel, Field
from typing import Optional

from app.services.narrative_service import generate_human_narrative, build_narrative_payload
from app.services.registry import get_audit_report   # your existing registry service

router = APIRouter(prefix="/api/v1", tags=["narrative"])


class NarrativeRequest(BaseModel):
    annual_decisions: int = Field(
        default=10_000,
        ge=100,
        le=10_000_000,
        description="Number of decisions this system makes per year. Used only for scale math.",
    )


class ImpactStats(BaseModel):
    """
    The numbers section of the response — always from the math engine, never from Gemini.
    The UI renders these directly. Gemini's prose references them but does not compute them.
    """
    per_1000_gap:             int
    unfair_per_year:          int
    privileged_rate_pct:      int
    unprivileged_rate_pct:    int
    privileged_group:         str
    unprivileged_group:       str
    protected_attribute:      str
    outcome_gap_pp:           float
    dir_score:                float


class NarrativeResponse(BaseModel):
    audit_id:         str
    annual_decisions: int

    # Engine numbers — the UI always uses these for stats, not Gemini's prose
    impact_stats:     ImpactStats

    # Gemini output — words only
    opening_line:     str
    person_story:     str
    scale_statement:  str
    what_changes:     str
    closing_call:     str

    # Transparency
    generated_by:     str    # "gemini-2.5-flash-lite" or "fallback"
    caution:          str    # always shown in the UI footer


STANDARD_CAUTION = (
    "This narrative was generated by Gemini based on numbers from ProxyGuard's math engine. "
    "All figures (per_1000_gap, unfair_per_year, outcome rates) are computed values from the audit — "
    "Gemini was instructed only to write words, not to compute or estimate. "
    "Verify all figures against the full audit report before making decisions."
)


@router.post("/audit/{audit_id}/narrative", response_model=NarrativeResponse)
async def get_human_narrative(audit_id: str, body: NarrativeRequest):
    """
    Generates the human impact narrative for a completed audit.

    Flow:
      1. Load the audit report from registry
      2. Build structured payload (numbers only, from the math engine)
      3. Send to Gemini with strict system prompt (words only, no math)
      4. Return narrative + raw impact numbers separately

    The client (HumanStoryPanel.tsx) renders impact numbers from impact_stats,
    and renders prose from the narrative fields. They are never mixed.
    """
    # Load audit
    report = await get_audit_report(audit_id)
    if not report:
        raise HTTPException(status_code=404, detail=f"Audit {audit_id} not found")

    # Build the payload — structured JSON for Gemini
    payload = build_narrative_payload(report, body.annual_decisions)

    # Generate narrative via Gemini (with deterministic fallback)
    narrative = await generate_human_narrative(report, body.annual_decisions)

    # Build impact stats from engine output — never from narrative
    go = (report.get("group_outcomes") or [{}])[0]
    priv_rate   = go.get("privileged_rate",   0.0)
    unpriv_rate = go.get("unprivileged_rate", 0.0)
    gap         = abs(priv_rate - unpriv_rate)

    return NarrativeResponse(
        audit_id         = audit_id,
        annual_decisions = body.annual_decisions,
        impact_stats     = ImpactStats(
            per_1000_gap          = round(gap * 1000),
            unfair_per_year       = round(body.annual_decisions * gap * 0.5),
            privileged_rate_pct   = round(priv_rate * 100),
            unprivileged_rate_pct = round(unpriv_rate * 100),
            privileged_group      = go.get("privileged_group",   "privileged group"),
            unprivileged_group    = go.get("unprivileged_group", "disadvantaged group"),
            protected_attribute   = go.get("protected_attribute", "protected attribute"),
            outcome_gap_pp        = round(gap * 100, 1),
            dir_score             = round(report.get("overall_dir_score", 0), 3),
        ),
        opening_line     = narrative.opening_line,
        person_story     = narrative.person_story,
        scale_statement  = narrative.scale_statement,
        what_changes     = narrative.what_changes,
        closing_call     = narrative.closing_call,
        generated_by     = narrative.generated_by,
        caution          = STANDARD_CAUTION,
    )
